/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CarDetails;
import model.CarHistory;

/**
 *
 * @author ajay09
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    CarHistory history;
    public ViewJPanel(CarHistory history) {
        initComponents();
        this.history = history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lblTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblSerialNumber = new javax.swing.JLabel();
        lblManufacturedYear = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtManufacturedYear = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        lblSeatsAvailable = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        chkBoxAvailability = new javax.swing.JCheckBox();
        lblMaintenanceCert = new javax.swing.JLabel();
        chkBoxMaintenanceCert = new javax.swing.JCheckBox();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(700, 700));

        lblTitle.setBackground(new java.awt.Color(153, 153, 153));
        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblTitle.setText("View Car Details");
        lblTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTitleActionPerformed(evt);
            }
        });

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Model", "Cars Available", "Seats", "Location", "Year", "Manufacturer", "Serial Number", "License Number", "Model Number"
            }
        ));
        tblCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCars);

        btnView.setBackground(new java.awt.Color(153, 153, 153));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblSerialNumber.setText("Serial Number :");

        lblManufacturedYear.setText("Manufactured Year :");

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        lblModel.setText("Model Name : ");

        lblModelNumber.setText("Model Number : ");

        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        lblSeatsAvailable.setText("No. of Seats Available :");

        lblAvailability.setText("Availability :");

        lblLicenseNumber.setText("License Number :");

        lblManufacturer.setText("Manufacturer :");

        lblLocation.setText("Location :");

        btnUpdate.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblMaintenanceCert.setText("Maintenance Certificate :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(lblAvailability)
                            .addComponent(lblSeatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkBoxAvailability)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtModelNumber)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtManufacturedYear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(10, 10, 10)
                        .addComponent(btnDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaintenanceCert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBoxMaintenanceCert)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLicenseNumber, txtLocation, txtManufacturedYear, txtManufacturer, txtModel, txtModelNumber, txtSeats, txtSerialNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAvailability, lblLicenseNumber, lblManufacturedYear, lblManufacturer, lblModel, lblModelNumber, lblSeatsAvailable, lblSerialNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModel)
                                .addGap(18, 18, 18)
                                .addComponent(lblModelNumber)
                                .addGap(18, 18, 18)
                                .addComponent(lblSerialNumber)
                                .addGap(18, 18, 18)
                                .addComponent(lblManufacturedYear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicenseNumber)
                            .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManufacturer)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeatsAvailable)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocation)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvailability)
                    .addComponent(chkBoxAvailability)
                    .addComponent(lblMaintenanceCert)
                    .addComponent(chkBoxMaintenanceCert))
                .addGap(438, 438, 438))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chkBoxAvailability, chkBoxMaintenanceCert, lblAvailability, lblLicenseNumber, lblLocation, lblMaintenanceCert, lblManufacturedYear, lblManufacturer, lblModel, lblModelNumber, lblSeatsAvailable, lblSerialNumber, txtLicenseNumber, txtLocation, txtManufacturedYear, txtManufacturer, txtModel, txtModelNumber, txtSeats, txtSerialNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void lblTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTitleActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectedRowIndex = tblCars.getSelectedRow();
        if (selectedRowIndex <0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        CarDetails selectedCars = (CarDetails) model.getValueAt(selectedRowIndex, 0);
        
        chkBoxAvailability.setText(String.valueOf(selectedCars.isAvailability()));
        txtLicenseNumber.setText(selectedCars.getLicenseNumber());
        txtLocation.setText(selectedCars.getLocation());
        txtManufacturedYear.setText(String.valueOf(selectedCars.getYear()));
        txtManufacturer.setText(selectedCars.getManufacturer());
        txtModel.setText(selectedCars.getModel());
        txtModelNumber.setText(String.valueOf(selectedCars.getModelNumber()));
        txtSeats.setText(String.valueOf(selectedCars.getSeats()));
        txtSerialNumber.setText(String.valueOf(selectedCars.getSerialNumber()));
        chkBoxMaintenanceCert.setText(String.valueOf(selectedCars.isMaintenanceCert()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRowIndex = tblCars.getSelectedRow();
        if (selectedRowIndex <0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        CarDetails selectedCars = (CarDetails) model.getValueAt(selectedRowIndex, 0);
        history.deleteCars(selectedCars);
        
        JOptionPane.showMessageDialog(this, "Car Detials deleted");
        
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        if(txtManufacturer.getText() == null || "".equals(txtManufacturer.getText()) || !Pattern.matches("^[a-zA-Z]+$", txtManufacturer.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid manufacturer name");
        return;
        }
        else if(txtModel.getText() == null || "".equals(txtModel.getText()) || !Pattern.matches("^[a-zA-Z]+$", txtModel.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid model");
        }
        else if(txtModelNumber.getText() == null || "".equals(txtModelNumber.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid Model Number");
        }
        else if(txtManufacturedYear.getText() == null || "".equals(txtManufacturedYear.getText()) || !Pattern.matches("^[0-9]{4}$", txtManufacturedYear.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid manufacturing year");
        }
        else if(txtSeats.getText() == null || "".equals(txtSeats.getText()) || !Pattern.matches("^[0-9]+$", txtSeats.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid seats");
        }
        else if(txtLocation.getText() == null || "".equals(txtLocation.getText()) || !Pattern.matches("^[a-zA-Z]+$", txtLocation.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid city");
        }
        else if(txtSerialNumber.getText() == null || "".equals(txtSerialNumber.getText()) || !Pattern.matches("^[0-9]+", txtSerialNumber.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid serial number");
        }
        else if(txtLicenseNumber.getText() == null || "".equals(txtLicenseNumber.getText()) || !Pattern.matches("^[0-9]+$", txtLicenseNumber.getText())){
        JOptionPane.showMessageDialog(this, "Please enter valid License Number");
        }
        else {
        int i = tblCars.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        CarDetails selectedCars = (CarDetails)model.getValueAt(i, 0);
        
        selectedCars.setManufacturer(txtManufacturer.getText());
        selectedCars.setModel(txtModel.getText());
        selectedCars.setYear(Integer.parseInt(txtManufacturedYear.getText()));
        selectedCars.setSeats(Byte.parseByte(txtSeats.getText()));
        selectedCars.setLocation(txtLocation.getText());
        selectedCars.setAvailability(chkBoxAvailability.isSelected());
        selectedCars.setLicenseNumber(txtLicenseNumber.getText());
        selectedCars.setMaintenanceCert(chkBoxMaintenanceCert.isSelected());
        //selectedCars.setCertificate(txtCarCertificate.getText());
        history.updateCars(i, selectedCars);
        
        JOptionPane.showMessageDialog(this, "Car Details Updated Successfully !!!");
        
        if(i>=0){
            model.setValueAt(txtModel.getText(), i, 0);
            model.setValueAt(chkBoxAvailability.isSelected(), i, 1);
            model.setValueAt(txtSeats.getText(), i, 2);
            model.setValueAt(txtLocation.getText(), i, 3);
            model.setValueAt(txtManufacturedYear.getText(), i, 4);
            model.setValueAt(txtManufacturer.getText(), i, 5);
            model.setValueAt(txtSerialNumber.getText(), i, 6);
            model.setValueAt(txtLicenseNumber.getText(), i, 7);
            model.setValueAt(txtModelNumber.getText(), i, 8);
            //model.setValueAt(txtModelNumber.getText(), i, 8);
            
            //model.setValueAt(txtSeats.getText(), i, 5);
            
            //model.setValueAt(txtCarCertificate.getText(), i, 7);

        }else{
            JOptionPane.showMessageDialog(null, "Error");
        }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    private void tblCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCarsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkBoxAvailability;
    private javax.swing.JCheckBox chkBoxMaintenanceCert;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMaintenanceCert;
    private javax.swing.JLabel lblManufacturedYear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSeatsAvailable;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JTextField lblTitle;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        for(CarDetails cd : history.getHistory()){
            
            Object[] row = new Object[9];
            row[0] = cd;
            row[1] = cd.isAvailability();
            row[2] = cd.getSeats();
            row[3] = cd.getLocation();
            row[4] = cd.getYear();
            row[5] = cd.getManufacturer();
            row[6] = cd.getSerialNumber();
            row[7] = cd.getLicenseNumber();
            row[8] = cd.getModelNumber();
            
            model.addRow(row);
        }
    }
}
